<?php
return [
    [
        'menu_name' => '商城系统',
        'menu_key' => 'shop',
        'menu_short_name' => '商城',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '110',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '概况',
                'menu_key' => 'shop_index',
                'menu_short_name' => '概况',
                'menu_type' => '1',
                'icon' => 'iconfont-icongaikuang1',
                'api_url' => 'index',
                'router_path' => 'shop/index',
                'view_path' => 'index/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '商品管理',
                'menu_key' => 'shop_goods',
                'menu_short_name' => '商品',
                'menu_type' => '0',
                'icon' => 'iconfont-iconshangpinguanli',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '商品列表',
                        'menu_key' => 'shop_goods_list',
                        'menu_short_name' => '商品列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinliebiao1',
                        'api_url' => 'goods',
                        'router_path' => 'shop/goods/list',
                        'view_path' => 'goods/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品分类',
                        'menu_key' => 'shop_goods_category_list',
                        'menu_short_name' => '商品分类',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinfenlei',
                        'api_url' => 'goods/category',
                        'router_path' => 'shop/goods/category',
                        'view_path' => 'goods/category',
                        'methods' => 'get',
                        'sort' => '89',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品标签',
                        'menu_key' => 'shop_goods_label_list',
                        'menu_short_name' => '商品标签',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinbiaoqian',
                        'api_url' => 'goods/label',
                        'router_path' => 'shop/goods/label',
                        'view_path' => 'goods/label_list',
                        'methods' => 'get',
                        'sort' => '87',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品品牌',
                        'menu_key' => 'shop_goods_brand_list',
                        'menu_short_name' => '商品品牌',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinpinpai',
                        'api_url' => 'goods/brand',
                        'router_path' => 'shop/goods/brand',
                        'view_path' => 'goods/brand_list',
                        'methods' => 'get',
                        'sort' => '86',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品服务',
                        'menu_key' => 'shop_goods_service_list',
                        'menu_short_name' => '商品服务',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinfuwu',
                        'api_url' => 'goods/service',
                        'router_path' => 'shop/goods/service',
                        'view_path' => 'goods/service',
                        'methods' => 'get',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '回收站',
                        'menu_key' => 'shop_goods_recycle_list',
                        'menu_short_name' => '回收站',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconhuishouzhan',
                        'api_url' => 'goods/recycle',
                        'router_path' => 'shop/goods/recycle',
                        'view_path' => 'goods/recycle',
                        'methods' => 'get',
                        'sort' => '84',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '分类设置',
                        'menu_key' => 'shop_goods_category_config',
                        'menu_short_name' => '分类设置',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconfenleishezhi',
                        'api_url' => '',
                        'router_path' => 'shop/goods/category/config',
                        'view_path' => 'goods/category_config',
                        'methods' => '',
                        'sort' => '82',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品添加',
                        'menu_key' => 'shop_goods_real_add',
                        'menu_short_name' => '商品添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/goods/real_edit',
                        'view_path' => 'goods/real_edit',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商品编辑',
                        'menu_key' => 'shop_goods_real_edit',
                        'menu_short_name' => '商品编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'goods/<id>',
                        'router_path' => 'shop/goods/real_edit',
                        'view_path' => 'goods/real_edit',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商品添加',
                        'menu_key' => 'shop_goods_virtual_add',
                        'menu_short_name' => '商品添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/goods/virtual_edit',
                        'view_path' => 'goods/virtual_edit',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商品编辑',
                        'menu_key' => 'shop_goods_virtual_edit',
                        'menu_short_name' => '商品编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'goods/<id>',
                        'router_path' => 'shop/goods/virtual_edit',
                        'view_path' => 'goods/virtual_edit',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '商品删除',
                        'menu_key' => 'shop_goods_delete',
                        'menu_short_name' => '商品删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'goods/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '订单管理',
                'menu_key' => 'shop_order',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'iconfont-iconshangpinguanli',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'shop_order_list',
                        'menu_short_name' => '订单列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont-icona-dingdanliebiao',
                        'api_url' => 'order/list',
                        'router_path' => 'shop/order/index',
                        'view_path' => 'order/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '退款维权',
                        'menu_key' => 'shop_order_refund',
                        'menu_short_name' => '退款维权',
                        'menu_type' => '1',
                        'icon' => 'iconfont-icondingdanweiquan',
                        'api_url' => '',
                        'router_path' => 'shop/order/refund',
                        'view_path' => 'order/refund',
                        'methods' => 'get',
                        'sort' => '89',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '发票管理',
                        'menu_key' => 'shop_invoice',
                        'menu_short_name' => '发票管理',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconfapiaoguanli',
                        'api_url' => '',
                        'router_path' => 'shop/order/invoice',
                        'view_path' => 'order/invoice',
                        'methods' => 'get',
                        'sort' => '88',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品评价',
                        'menu_key' => 'shop_goods_evaluate',
                        'menu_short_name' => '商品评价',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinpinglun',
                        'api_url' => 'goods/evaluate',
                        'router_path' => 'shop/order/evaluate',
                        'view_path' => 'goods/evaluate',
                        'methods' => 'get',
                        'sort' => '87',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '订单设置',
                        'menu_key' => 'shop_config_order',
                        'menu_short_name' => '订单设置',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconjiaoyishezhi',
                        'api_url' => 'order/config',
                        'router_path' => 'shop/order/order/config',
                        'view_path' => 'order/config',
                        'methods' => '',
                        'sort' => '86',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商家地址库',
                        'menu_key' => 'shop_address',
                        'menu_short_name' => '商家地址库',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangjiadizhiku',
                        'api_url' => '',
                        'router_path' => 'shop/order/address',
                        'view_path' => 'address/list',
                        'methods' => 'get',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '配送设置',
                        'menu_key' => 'shop_config_delivery',
                        'menu_short_name' => '配送设置',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconpaisongshezhi',
                        'api_url' => '',
                        'router_path' => 'shop/order/delivery',
                        'view_path' => 'delivery/config',
                        'methods' => '',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '维权详情',
                        'menu_key' => 'shop_order_refund_detail',
                        'menu_short_name' => '维权详情',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinguanli',
                        'api_url' => '',
                        'router_path' => 'shop/order/refund/detail',
                        'view_path' => 'order/refund_detail',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加评价',
                        'menu_key' => 'shop_goods_evaluate_add',
                        'menu_short_name' => '添加评价',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'goods/evaluate',
                        'router_path' => 'shop/order/evaluate/add',
                        'view_path' => 'goods/evaluate_edit',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '物流跟踪',
                        'menu_key' => 'shop_config_delivery_search',
                        'menu_short_name' => '物流跟踪',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconwuliugenzong',
                        'api_url' => '',
                        'router_path' => 'shop/order/delivery/search',
                        'view_path' => 'delivery/search',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '配送员',
                        'menu_key' => 'shop_config_delivery_staff',
                        'menu_short_name' => '配送员',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/order/delivery/staff',
                        'view_path' => 'delivery/staff',
                        'methods' => '',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '自提点',
                        'menu_key' => 'shop_config_shop_delivery_store',
                        'menu_short_name' => '自提点',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'shop/store',
                        'router_path' => 'shop/order/delivery/store',
                        'view_path' => 'delivery/store',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加自提点',
                        'menu_key' => 'shop_config_edit_delivery_store',
                        'menu_short_name' => '添加自提点',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'shop/store',
                        'router_path' => 'shop/order/delivery/store/edit',
                        'view_path' => 'delivery/store_edit',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '物流公司',
                        'menu_key' => 'shop_config_delivery_company',
                        'menu_short_name' => '物流公司',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/order/delivery/company',
                        'view_path' => 'delivery/company',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单详情',
                        'menu_key' => 'shop_order_detail',
                        'menu_short_name' => '订单详情',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconshangpinguanli',
                        'api_url' => 'order/detail<id>',
                        'router_path' => 'shop/order/detail',
                        'view_path' => 'order/detail',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '运费模版',
                        'menu_key' => 'shop_config_delivery_shipping_template',
                        'menu_short_name' => '运费模版',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/order/shipping/template',
                        'view_path' => 'delivery/template',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '运费模版添加/编辑',
                        'menu_key' => 'shop_config_delivery_shipping_template_edit',
                        'menu_short_name' => '运费模版添加/编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/order/shipping/template_edit',
                        'view_path' => 'delivery/template_edit',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加/编辑地址',
                        'menu_key' => 'shop_address_edit',
                        'menu_short_name' => '添加/编辑地址',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/order/address/edit',
                        'view_path' => 'address/edit',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '同城配送',
                        'menu_key' => 'shop_config_delivery_local',
                        'menu_short_name' => '同城配送',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/order/delivery/local',
                        'view_path' => 'delivery/local',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '店铺营销',
                'menu_key' => 'shop_goods_marketing',
                'menu_short_name' => '营销',
                'menu_type' => '0',
                'icon' => 'iconfont-iconshangpinguanli',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '优惠券',
                        'menu_key' => 'shop_goods_coupon_list',
                        'menu_short_name' => '优惠券',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconyouhuiquan',
                        'api_url' => '',
                        'router_path' => 'shop/marketing/coupon/list',
                        'view_path' => 'marketing/coupon/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '优惠券领取记录',
                        'menu_key' => 'shop_goods_coupon_collection',
                        'menu_short_name' => '优惠券领取记录',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/marketing/coupon/collection',
                        'view_path' => 'marketing/coupon/collection',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '营销中心',
                        'menu_key' => 'shop_goods_marketing_index',
                        'menu_short_name' => '营销中心',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconyingxiaozhongxin',
                        'api_url' => '',
                        'router_path' => 'shop/marketing/index',
                        'view_path' => 'marketing/index',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '优惠券添加',
                        'menu_key' => 'shop_goods_coupon_add',
                        'menu_short_name' => '优惠券添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/marketing/coupon/add',
                        'view_path' => 'marketing/coupon/add',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '优惠券编辑',
                        'menu_key' => 'shop_goods_coupon_edit',
                        'menu_short_name' => '优惠券编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'shop/marketing/coupon/edit',
                        'view_path' => 'marketing/coupon/edit',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '优惠券删除',
                        'menu_key' => 'shop_goods_coupon_delete',
                        'menu_short_name' => '优惠券删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];